name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Installation des dépendances
        run: bun install

      - name: Vérification du lint
        run: bun run lint

  check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Installation des dépendances
        run: bun install

      - name: Vérification svelte-check
        run: bun run check

#   test:
#     name: Tests unitaires (Vitest)
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout du code
#         uses: actions/checkout@v4

#       - name: Setup Bun
#         uses: oven-sh/setup-bun@v2

#       - name: Installation des dépendances
#         run: bun install

#       - name: Exécution des tests unitaires
#         run: bun run test:unit
